# railway.toml
[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/mcp/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
HOST = "0.0.0.0"
PORT = "8000"