services:
  - type: web
    name: mcp-simple-server
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    healthCheckPath: /mcp/
    autoDeploy: true
    branch: main
